client_config_backend: file
client_config_file: auth/client_secrets.json
client_config:
  client_id:
  client_secret:

save_credentials: True
save_credentials_backend: file
save_credentials_file: auth/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
